spring:
  datasource:
    password: sa
    username: postgres
    url: jdbc:postgresql://localhost:5432/ca_mercadofinanceiro

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true

      


     
