spring:
  datasource:
    password: sa
    username: postgres
    url: jdbc:postgresql://localhost:5432/ca_investimentos
  jpa:
    properties:
      temp:
        use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: update
      show-sql: true
      jdbc:
        lob:
          non_contextual_creation: true
      
        
      


     
